### ISSUE TITLE
Int Validation fails when last_change param is passed

### ISSUE THREAD

**Issue by bbriggs** [rnelson0/puppet-local_user#19]
It appears to be failing only when I pass the last change param in via Hiera.

```yaml
local_users:
    sftp_user:
        state:              'present'
        comment:            'foo'
        home:               '/incoming'
        password_max_age:   '9999'
        last_change:        '2015-12-12'
        shell:              '/sbin/nologin'
        groups:
        - 'sftp_gen'
        - 'sftp_write'
        password:       'crypted_string'
```

and 
```puppet
    if ($local_users != undef) {
        create_resources('local_user', $local_users)
    }
```

Produces this:
`Error 400 on SERVER: validate_integer(): Expected first argument to be an Integer or Array, got String at /etc/puppet/environments/accounts_test/modules/local_user/manifests/init.pp:52`

This behavior goes away when I remove the `last_change` parameter in Hiera. 

Client details:
```
[root@client /]# puppet --version
3.8.3
[root@client /]# ruby --version
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
[root@client /]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.7 (Santiago)
```

Server details:
```
root@puppetserver:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```
