### ISSUE TITLE
Managegroups parameter causing duplicate declarations

### ISSUE THREAD

**Issue by bbriggs** [rnelson0/puppet-local_user#37]
```
Error: Duplicate declaration: Group[wheel] is already declared in file /etc/puppet/modules/local_user/manifests/init.pp:69; cannot redeclare at /etc/puppet/modules/local_user/manifests/init.pp:69 on node router.sithmail.com
```

node01.yaml:
```yaml
---
local_users:
    bar:
        state:            'present'
        home:             '/home/bar'
        managehome:       true
        comment:          'bar'
        groups:
            - wheel
        gid:              'bar'
        password:         ''
        manage_groups:    true
        password_max_age: '1000'
        ssh_authorized_keys:
            - 'ssh-rsa AAAA...1234 bar@localhost'
```

common.yaml:
```yaml
local_users:
    briggsb:
        state:            'present'
        home:             '/home/briggsb'
        managehome:       true
        comment:          'briggsb'
        groups:
          - 'wheel'
        gid:              'briggsb'
        manage_groups:    true
        last_change:      '2016-01-01'
        password:         ''
        password_max_age: '1000'
        ssh_authorized_keys:
          - 'ssh-rsa AAAA...mypubkey briggsb@localhost'
```

site.pp:
```puppet
    $users = hiera_hash('local_users', undef) 
    create_resources('local_user', $users)
```

Was also able to duplicate this with both users being in the same hash in common.yaml
