### ISSUE TITLE
Deeper merge: ssh_authorized_keys in two locations results in duplicate resources

### ISSUE THREAD

**Issue by bbriggs** [rnelson0/puppet-local_user#39]
Error:
```
Error: Duplicate declaration: Ssh_authorized_key[bar_ssh-rsa_bar@localhost] is already declared in file /etc/puppet/modules/local_user/manifests/ssh_authorized_keys.pp:32; cannot redeclare at /etc/puppet/modules/local_user/manifests/ssh_authorized_keys.pp:32 on node node.example.com
```

hiera.yaml:
```yaml
---
:backends:
  - yaml
  - json
:yaml:
  :datadir: /etc/puppet/hieradata
:json:
  :datadir: /etc/puppet/hieradata
:hierarchy:
  - "node/%{::fqdn}"
  - "%{::operatingsystem}"
  - "common"
:merge_behavior: deeper
```
node.yaml:
```
local_users:
    bar:
        state:            'present'
        home:             '/home/bar'
        managehome:       true
        comment:          'bar'
        groups:
            - wheel
        gid:              'bar'
        password:         ''
        password_max_age: '1000'
        ssh_authorized_keys:
            - 'ssh-rsa AAAA...1234 bar@localhost'
```

common.yaml:
```yaml
    bar:
        state:            'absent'
        home:             '/home/bar'
        managehome:       true
        comment:          'bar'
        groups:
            - wheel
        gid:              'bar'
        password:         ''
        password_max_age: '1000'
        ssh_authorized_keys:
            - 'ssh-rsa AAAA..1234 bar@localhost'
```

site.pp:
```puppet
$users  = hiera_hash('local_users', undef)
if ($users != undef) {
    create_resources('local_user', $users)
}
```

hash:
```
bar"=>
  {"state"=>"present",
   "home"=>"/home/bar",
   "managehome"=>true,
   "comment"=>"bar",
   "groups"=>["wheel"],
   "gid"=>"bar",
   "password"=>"",
   "password_max_age"=>"1000",
   "ssh_authorized_keys"=>
    ["ssh-rsa AAAA...1234 bar@localhost"]}
```
